### PR TITLE
Change in cloudformation: DynamoDB table for Oscar winner predictions

### PR DESCRIPTION
**Pull request by shtukas**

### CODE REVIEW

**Comment by tomrf1** [comment]
Why do you need indexes on each category?

**Comment by shtukas** [comment]
We actually don't. Let me update that.

@annebyrne

**Comment by shtukas** [comment]
@tomrf1 @annebyrne Updated! Also while being at it, I have renamed `bestFilm` into `bestPicture`.

**Comment by tomrf1** [comment]
Great. And now that the `best*` fields are no longer used in indexes, you can remove them from the cloudformation completely. I think your template will actually be rejected if you leave them in.
The app will decide the names/types of these fields.

**Comment by shtukas** [comment]
Oh. That's useful to know. Give me one sec.

**Comment by shtukas** [comment]
Ok done, only `ID` is required.

**Comment by tomrf1** [comment]
👍

**Pull request merged**
