### PR TITLE
Update stack to allow reading of Oscars SQS queue

### PR DESCRIPTION
**Pull request by annebyrne**

### CODE REVIEW

**Comment by LATaylor-guardian** [comment]
Looks okay to me 👍

**Comment by annebyrne** [comment]
Tested on CODE. Will wait for @tomrf1 +1 then merge.

**Comment by shtukas** [comment]
Me too :+1:

**Comment by LATaylor-guardian** [comment]
Looks good to me and you've tested on CODE. Merge it  :) 👍

**Comment by tomrf1** [comment]
💯

**Pull request merged**
