### PR TITLE
Better handling of errors after facebook requests

### PR DESCRIPTION
**Pull request by tomrf1**
It failed to get a user's info from FB while doing morning briefings today, and subsequently broke.

### CODE REVIEW

**Comment by cb372** [comment]
The nested ifs burn my eyes but 👍

**Comment by LATaylor-guardian** [comment]
Say no to if hell: http://ramdajs.com/0.22.1/docs/#cond

**Comment by LATaylor-guardian** [comment]
👍

**Comment by tomrf1** [comment]
The ramdajs thing looks good, might give it a go later. For now I've just flattened it a little :)

**Pull request merged**
